// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yteqzzzmrbqlnjdvdjtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0ZXF6enptcmJxbG5qZHZkanR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMjc4MDMsImV4cCI6MjA4MzkwMzgwM30.hPzg7wobsQ-eIjAn4iF_Asak9eNq3gAtNXkZBS8Ixn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});